#!/bin/sh

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "master" ] || [ "$branch" = "main" ]; then
    echo "Pushing to master/main branch is not allowed."
    echo "Please create a separate branch for your changes."
    exit 1
fi

exit 0